### ISSUE TITLE
Center Images

### ISSUE THREAD

**Issue by sofuca** [jbub/ghostwriter#35]
Hello I wish to centre some images and need to put the following code into the theme. But not sure where to put it. Perhaps it's worth putting it in as default?

http://www.ebadf.net/2016/10/19/centering-images-in-hugo/
```
img[src$='#center']
{
    display: block;
    margin: 0.7rem auto; /* you can replace the vertical '0.7rem' by
                            whatever floats your boat, but keep the
                            horizontal 'auto' for this to work */
    /* whatever else styles you fancy here */
}

img[src$='#floatleft']
{
    float:left;
    margin: 0.7rem;      /* this margin is totally up to you */
    /* whatever else styles you fancy here */
}

img[src$='#floatright']
{
    float:right;
    margin: 0.7rem;      /* this margin is totally up to you */
    /* whatever else styles you fancy here */
}
```

**Comment by jbub** [comment]
Hello thank you for a wonderful solution, should be fixed by f5705111276d4cf60ab0b8148433bf970392a0cb. 

You should be able to use it like this:

```markdown
![Centered image](https://gohugo.io/apple-touch-icon.png#align-center)
![Left aligned image](https://gohugo.io/apple-touch-icon.png#align-left)
![Right aligned image](https://gohugo.io/apple-touch-icon.png#align-right)
```

Thanks for your contribution!

**Comment by sofuca** [comment]
Hello, I've cloned your repo and updated my code. It works locally but when I push to S3 it doesn't work.

I've removed all files from my s3 bucket and pushed again and it still doesn't work. I also tried a totally new post.

The site is - https://terraformtraining.com

Any Ideas?
